name: reddit_clone
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^5.1.1
  flutter_riverpod: ^2.0.2
  custom_line_indicator_bottom_navbar: ^0.0.8
  firebase_auth: ^4.0.2
  firebase_storage: ^11.0.2
  firebase_core: ^2.1.0
  cached_network_image: ^3.2.2
  flutter_easyloading: ^3.0.5
  uuid: ^3.0.6
  image_picker: ^0.8.6
  fpdart: ^0.3.0
  dotted_border: ^2.0.0+2
  any_link_preview: ^2.0.9
  flutter_lints: ^2.0.1
  shared_preferences: ^2.0.15
  google_sign_in: ^5.4.2
  cloud_firestore: ^4.0.2
  routemaster: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
