// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBjBSHwXzVvaSzCCvR_s8E8Zg7sc8DXoBU',
    appId: '1:632690901665:web:3ec0ef8783929d0fc1a6e0',
    messagingSenderId: '632690901665',
    projectId: 'reddit-clone-21f38',
    authDomain: 'reddit-clone-21f38.firebaseapp.com',
    storageBucket: 'reddit-clone-21f38.appspot.com',
    measurementId: 'G-JKHD1SBV5T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtVDGml2420DblskwuGdp6VoA36YVF2cs',
    appId: '1:632690901665:android:55d9122d9db53356c1a6e0',
    messagingSenderId: '632690901665',
    projectId: 'reddit-clone-21f38',
    storageBucket: 'reddit-clone-21f38.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBgnRz9cdVRGRCgHT3a8m61JLwFnKqUUU',
    appId: '1:632690901665:ios:d080ed7ae738f5adc1a6e0',
    messagingSenderId: '632690901665',
    projectId: 'reddit-clone-21f38',
    storageBucket: 'reddit-clone-21f38.appspot.com',
    iosClientId: '632690901665-osh4ltik0uvtaeej3lt3s6lc5oq86qh5.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBgnRz9cdVRGRCgHT3a8m61JLwFnKqUUU',
    appId: '1:632690901665:ios:d080ed7ae738f5adc1a6e0',
    messagingSenderId: '632690901665',
    projectId: 'reddit-clone-21f38',
    storageBucket: 'reddit-clone-21f38.appspot.com',
    iosClientId: '632690901665-osh4ltik0uvtaeej3lt3s6lc5oq86qh5.apps.googleusercontent.com',
    iosBundleId: 'com.example.redditClone',
  );
}
